#!/usr/bin/env zsh


# ls
alias l='ls -oAh'
alias ll='ls -FlAh'
alias lt="ls -to"
alias la="ls -AFoh"
alias lat="ls -AFoth"


#  Files
alias cp='cp -iv'
alias mv='mv -iv'
alias mkdir='mkdir -pv'
mcd () { mkdir -p "$1" && cd "$1"; }


# Navigation
cd() { builtin cd "$@"; ll; }
alias ~="cd ~"


#  Terminal and shell
alias c='clear'
alias path='echo -e ${PATH//:/\\n}'


#  Mac specific
if [[ $(uname) == "Darwin" ]]; then
    alias DT='tee ~/Desktop/term_output.txt'
    alias f='open -a Finder ./'
    alias edit='code'
    trash () { command mv "$@" ~/.Trash ; }
fi
