#!/bin/bash

# bash_profile

######################################################################
#  PROMPT
######################################################################

if [[ $COLORTERM == gnome-* && $TERM == xterm ]] && infocmp gnome-256color >/dev/null 2>&1; then
    export TERM=gnome-256color
elif infocmp xterm-256color >/dev/null 2>&1; then
    export TERM=xterm-256color
fi

source $HOME/dotfiles/shell/bash_prompt


######################################################################
#  ENVIRONMENT VARIABLES
######################################################################


export PATH=${PATH}:${HOME}/Applications/Visual\ Studio\ Code.app/Contents/Resources/app/bin

#  Get WRDS username.
source ${HOME}/Dropbox/_config/wrds.sh


######################################################################
#  CONDA
######################################################################

. $HOME/anaconda3/etc/profile.d/conda.sh
conda activate


######################################################################
#  ALIASES AND FUNCTIONS
######################################################################

source $HOME/dotfiles/shell/bash_aliases


######################################################################
#  Idea sources:
#  - http://natelandau.com/my-mac-osx-bash_profile/
#  - https://github.com/necolas/dotfiles
#
######################################################################
