#!/bin/bash

# bash_profile

######################################################################
#  PROMPT
######################################################################

if [[ $COLORTERM == gnome-* && $TERM == xterm ]] && infocmp gnome-256color >/dev/null 2>&1; then
    export TERM=gnome-256color
elif infocmp xterm-256color >/dev/null 2>&1; then
    export TERM=xterm-256color
fi

source $HOME/dotfiles/shell/bash_prompt


######################################################################
#  ENVIRONMENT VARIABLES
######################################################################

#  Use Atom as default editor.
export EDITOR="/usr/local/bin/atom -w"
export PATH=${PATH}:${HOME}/Applications/Visual\ Studio\ Code.app/Contents/Resources/app/bin

#  Get WRDS username.
source ~/Dropbox/_config/wrds.sh


######################################################################
#  CONDA
######################################################################


if [ -z "${!CONDA_DEFAULT_ENV}" ]; then
	. $HOME/anaconda3/etc/profile.d/conda.sh
	conda activate
fi


######################################################################
#  ALIASES AND FUNCTIONS
######################################################################

#  ls
alias l='ls -A'
alias ls='ls -G'
alias ll='ls -FlA'
alias lf='ls -F'

#  File commands
alias cp='cp -iv'
alias mv='mv -iv'
alias mkdir='mkdir -pv'
mcd () { mkdir -p "$1" && cd "$1"; }

#  Navigation commands
cd() { builtin cd "$@"; ll; }
alias ~='cd ~'
alias ..='cd ../'
alias ..2='cd ../../'
alias ..3='cd ../../../'
alias ..4='cd ../../../../'
alias ..5='cd ../../../../../'

#  Terminal and shell
alias c='clear'
alias path='echo -e ${PATH//:/\\n}'
alias DT='tee ~/Desktop/term_output.txt'

#  Mac specific
alias f='open -a Finder ./'
alias edit='mate'
trash () { command mv "$@" ~/.Trash ; }
ql () { qlmanage -p "$*" >& /dev/null; }


######################################################################
#  Idea sources:
#  - http://natelandau.com/my-mac-osx-bash_profile/
#  - https://github.com/necolas/dotfiles
#
######################################################################
