# oh-my-zsh
export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="spaceship"

plugins=(
    rust
    git
    themes
    zsh-syntax-highlighting
    zsh-autosuggestions
    docker
    )

source $ZSH/oh-my-zsh.sh


# Spaceship
SPACESHIP_TIME_SHOW=true


# Aliases
source ${HOME}/dotfiles/shell/aliases


# macOS
if [[ $(uname) == "Darwin" ]]; then
    source "${HOME}/Library/Mobile Documents/com~apple~CloudDocs/_config/secrets.sh"

    export PATH=${PATH}:$HOME/.cargo/bin
    export PATH=/opt/homebrew/bin:${PATH}
    export PATH=${PATH}:${HOME}/Applications/Visual\ Studio\ Code.app/Contents/Resources/app/bin
fi
