
# oh-my-zsh
export ZSH="/Users/jkiley/.oh-my-zsh"
ZSH_THEME="spaceship"

plugins=(
    rust
    git
    themes
    zsh-syntax-highlighting
    zsh-autosuggestions
    docker
    )

source $ZSH/oh-my-zsh.sh


# Spaceship

SPACESHIP_TIME_SHOW=true


# Conda
__conda_setup="$('/opt/homebrew/Caskroom/miniforge/base/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/opt/homebrew/Caskroom/miniforge/base/etc/profile.d/conda.sh" ]; then
        . "/opt/homebrew/Caskroom/miniforge/base/etc/profile.d/conda.sh"
    else
        export PATH="/opt/homebrew/Caskroom/miniforge/base/bin:$PATH"
    fi
fi
unset __conda_setup


# Custom
source ${HOME}/dotfiles/shell/zsh_aliases
source "${HOME}/Library/Mobile Documents/com~apple~CloudDocs/_config/secrets.sh"

export PATH=${PATH}:$HOME/.cargo/bin
export PATH=/opt/homebrew/bin:${PATH}
export PATH=${PATH}:${HOME}/Applications/Visual\ Studio\ Code.app/Contents/Resources/app/bin
